# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f489bf043fbd15aa1afe8d36701442b0700c234cc444dd16ee5d6d3dab3fc060f7fa82c16331b6c14930f6db7e635a9c59eadff4762abe3b43383be77af9f29

test:
  secret_key_base: c8db362e3cf34ca6b706439c34dcea84518790ed067436360dd05b9b2bd9bc31e28ca2244538c62672b57a9dcf960a8ab90af88493acd153dfe19d0c9c86e574

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
